name: verlof_dagen_app
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter

  getwidget: ^2.0.5
  # Hive dependencies
  hive:
  hive_flutter:
  path_provider:

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Hive dependencies
  hive_generator:
  build_runner:

  # PopUp bucket
  get:

  # linting dependencies
  flutter_lints: ^1.0.0

  # splash dependencies
  flutter_native_splash:

flutter_native_splash:
  color: "#FFFFFF"
  color_dark: "#1a1a1a"
  image: lib/assets/images/vacation2.png
  android: true
  ios: true
  # ios_content_mode: scaleAspectFill

flutter:
  uses-material-design: true
  assets:
    - lib/assets/images/
